# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bdee6fcee278ad2a3e471cff7fd6ec1ad1c863abb8c89edefa6cebfab583ce7823ef8649812394b4cff5b025144284cfcd091c63863aeeba381f158032afd1

test:
  secret_key_base: 96603d4089896e54ce76be9ab07098d54b567389fde014ed1b8f4b4c47bc1c7bdd6e59a0a6f035a1f01ad7a6001d78d7cc0837647d6aebd757354057853f6526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
